server:
  context-path: /authserver
  port: 8080
management:
  security:
    enabled: false
  context-path: /mgmt
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tianyuan
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
