server:
  context-path: /authserver
  port: 8080
management:
  security:
    enabled: false
  context-path: /mgmt
spring:
  datasource:
    url: jdbc:mysql://192.168.116.199:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: toyo123
  jpa:
    show-sql: true
