# application.yml 可以用来定义应用级别的，如果搭配spring-cloud-config使用 application.yml里面定义的文件可以实现动态替换
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  application:
    name: config-service
  profiles:
    active: native
          
server:
  port: 8888

eureka: 
  instance:
    non-secure-port: 8761 
    preferIpAddress: true
    instance-id: localhost:${server.port}
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://192.168.118.14:1111/eureka
    



